### ISSUE TITLE
tutorial:events: Mixin @At target string invalid.

### ISSUE THREAD

**Issue by SirEnder125** [FabricMC/fabric-example-mod#100]
Hello. I was following the [event tutorial](https://fabricmc.net/wiki/tutorial:events) and the line:
```Java
@Inject(at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/passive/SheepEntity;dropItems()V"), method = "interactMob", cancellable = true)
```
is invalid because the string `"Lnet/minecraft/entity/passive/SheepEntity;dropItems()V"` can not be resolved. At least that's what IntelliJ IDEA MC Development plugin says

**Comment by ByMartrixx** [comment]
Looks like the wiki article is outdated: `#dropItems` isn't called from `#interactMob`, but from `#sheared`. You can change the At target to SheepEntity#sheared, which should have the same effect

**Comment by SirEnder125** [comment]
Okay. Thanks for the quick reply! :D
