### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-example-mod#101]
I can't build any mods. This is the output i get:

```
> Configure project :
Fabric Loom: 0.6.58 Build(release #58)

> Task :compileJava FAILED
C:\fabric-example-mod-master\fabric-example-mod-master\src\main\java\net\fabricmc\example\mixin\ExampleMixin.java:11: error: No obfuscation mapping for @Inject target init
        @Inject(at = @At("HEAD"), method = "init()V")
        ^
warning: The following options were not recognized by any processor: '[outMapFileNamedIntermediary, inMapFileNamedIntermediary]'
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BU¦LD FAILED in 4s
1 actionable task: 1 executed
```

This happens even if i don't modify anything.

**Comment by Technici4n** [comment]
Shouldn't it be `<init>`?

**Comment by antonilol** [comment]
looks like an outdated loom. you are using 0.6.58, change the version to 0.10-SNAPSHOT in build.gradle

**Comment by t0int** [comment]
> looks like an outdated loom. you are using 0.6.58, change the version to 0.10-SNAPSHOT in build.gradle

I have the same issue and i use fabric loom version **0.11.26** but i still have same error.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
