### ISSUE TITLE
Mappings not working / can't build

### ISSUE THREAD

**Issue by Thorben0** [FabricMC/fabric-example-mod#104]
When building or editing with IDE no minecraft related classes are found.
```
C:\Development\Java\moddev\example-mod\src\main\java\net\fabricmc\example\mixin\ExampleMixin.java:9: warning: Error processing public targets: java.lang.ClassCastException: class java.lang.String cannot be cast to class javax.lang.model.type.TypeMirror (java.lang.String is in module java.base of loader 'bootstrap'; javax.lang.model.type.TypeMirror is in module java.compiler of loader 'platform')
@Mixin(TitleScreen.class)
^
C:\Development\Java\moddev\example-mod\src\main\java\net\fabricmc\example\mixin\ExampleMixin.java:9: error: Mixin has no targets
@Mixin(TitleScreen.class)
^
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
C:\Development\Java\moddev\example-mod\src\main\java\net\fabricmc\example\mixin\ExampleMixin.java:3: error: package net.minecraft.client.gui.screen does not exist
import net.minecraft.client.gui.screen.TitleScreen;
                                      ^
C:\Development\Java\moddev\example-mod\src\main\java\net\fabricmc\example\mixin\ExampleMixin.java:9: error: cannot find symbol
@Mixin(TitleScreen.class)
       ^
  symbol: class TitleScreen
3 errors
3 warnings
```

Freshtly cloned example project with latest yarn mappings (1.17+build.1)

**Comment by StoneLabs** [comment]
Can confirm. Fresh clone not building.
It does however build after removing the example mixin in the example mod.

**Comment by StoneLabs** [comment]
Can confirm, does not build after fda2a1cf1e329ed33f111d3e29d3269faf94d597.

**Comment by StoneLabs** [comment]
Upgrading https://github.com/FabricMC/fabric-example-mod/blob/fda2a1cf1e329ed33f111d3e29d3269faf94d597/gradle.properties#L7 to `1.17+build.5` fixed it.

**Comment by sfPlayer1** [comment]
Are you sure it didn't just fail to prepare the remapped mc jar?

**Comment by StoneLabs** [comment]
Yes. A fresh clone did not build multiple times just a couple minutes ago.

However I just tried again and it appears to build just fine now. Odd...

**Comment by SFort** [comment]
switching to 1.17+build.5 fixes nothing for me

**Comment by sfPlayer1** [comment]
A fresh clone doesn't reset everything since loom puts relevant data in ~/.gradle/caches/fabric-loom - you'd have to run gradle with --refresh-dependencies I think.

**Comment by StoneLabs** [comment]
> 
> 
> A fresh clone doesn't reset everything since loom puts relevant data in ~/.gradle/caches/fabric-loom - you'd have to run gradle with --refresh-dependencies I think.

This appears to have been the issue for me. I retract all my statements, fresh clone and clearing ~/.gradle works just fine.

**Comment by tyleraharrison** [comment]
Clearing gradle, running with --refresh-dependencies, then running `gradle genSources` before I build did the trick for me
