### ISSUE TITLE
Could not resolve all files for configuration ':modCompileClasspath'. —_—

### ISSUE THREAD

**Issue by OneDefauter** [FabricMC/fabric-example-mod#106]
![Screenshot_35](https://user-images.githubusercontent.com/27703239/121757844-52ce9280-caf5-11eb-9f50-2a3bd340c744.jpg)
1.17
JDK 16

**Comment by OroArmor** [comment]
not an issue with fabric, but shedaniel has moved their maven to a different location. its listed on the rei page

**Comment by OneDefauter** [comment]
> not an issue with fabric, but shedaniel has moved their maven to a different location. its listed on the rei page

Thanks.
