### ISSUE TITLE
Run Configurations Not Appearing

### ISSUE THREAD

**Issue by saoj12** [FabricMC/fabric-example-mod#107]
I'm using IntelliJ and trying to set up a new fabric mod from the example mod, but whenever I open it the run configuration is not visible in the top right corner of the IDE, and the 'run' folder of the project is empty.

Things I have tried:

1. Closing and re-opening the project
2. Re-importing the gradle project from the gradle tab
3. Using an example mod with the build.gradle and gradle.properties edited according to the tutorial on the wiki
4. Using a completely fresh example mod download
5. Deleting the '.gradle. folder and refreshing the project
6.  Refreshing gradle dependencies

Any help would be appreciated

**Comment by mochen-six** [comment]
like this
[https://sm.ms/image/LlFsep5rTx2AHaM](url)Image

**Comment by saoj12** [comment]
> like this
> [Image](https://sm.ms/image/LlFsep5rTx2AHaM)

I have tried that, that's what I meant by 'Re-importing the gradle project from the gradle tab'

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
