### ISSUE TITLE
RangeDecoratorConfig() not working in 1.17

### ISSUE THREAD

**Issue by BernardWasTaken** [FabricMC/fabric-example-mod#109]
hey, I wanted to ask what is the new RangeDecoratorConfig() in 1.17... I heard that it changed to something else due to new 1.17 world generation... any help is welcome. thank you

**Comment by AfraidMonster** [comment]
(new RangeDecoratorConfig(UniformHeightProvider.create(YOffset.fixed(0), YOffset.fixed(
	  100)))))
    .spreadHorizontally()
    .repeat(5); this should work in 1.17

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
