### ISSUE TITLE
Where to find example mod for 1.16.5

### ISSUE THREAD

**Issue by M1ntcraft3r** [FabricMC/fabric-example-mod#115]
Sorry if this is a stupid question, but I have been looking everywhere for the example mod for 1.16.5.
My understanding is that 1.17 requires java 16, whereas previous versions use java 8 (1.8)
I'd like to port my 1.16 forge mod to fabric, the server I am on is still 1.16.5 and I thought it would be a good starting point to try and get that going first.

Thanks

**Comment by Technici4n** [comment]
It looks like it's on the [`master` branch](https://github.com/FabricMC/fabric-example-mod/tree/master).

**Comment by M1ntcraft3r** [comment]
> It looks like it's on the [`master` branch](https://github.com/FabricMC/fabric-example-mod/tree/master).

Great, thanks!
I looks like that's correct and I will close this ticket shortly.
Only other question would be, should this not be in a 1.16.5 brach ?
That what I would have expected tbh. It would be a shame I'm someone merged future code in masters, removing the 1.16.5 compatibility.
On the other hand, I'm sure you guys got it under control
