### ISSUE TITLE
How to use this example to build 1.16.5 mod

### ISSUE THREAD

**Issue by T4M-Moling** [FabricMC/fabric-example-mod#117]
I want to build the 1.16.5 mod, but when I build the project, the fabric loader says it needs minecraft 1.17

**Comment by StoneLabs** [comment]
On github you can look at the history by [clicking on commits in the top right](https://stackoverflow.com/a/63925422) when browsing the code of the repositry.

You can then use an older commit of this repository like [this one](https://github.com/FabricMC/fabric-example-mod/tree/29c522536fc16233833221e22eed3f106c0726bc), which seems to be the last commit targeted for 1.16.5.

You can then just download the code as you usually do with download as zip.
![image](https://user-images.githubusercontent.com/19885942/125615764-d258cb6e-cdd5-4959-abb4-c69573097680.png)

~ Stone

**Comment by nebspacefarer** [comment]
Hello.

Another solution is just to select the master branch on the Github repository, which is the version corresponding to 1.16.5.
Directly on Github website, you can switch branches from this dropdown menu:

![image](https://user-images.githubusercontent.com/65596181/125615884-5ed29472-c3e1-4b5a-bfe6-5b09f577d8ca.png)

**Comment by SolidBlock-cn** [comment]
You can also just check this page: https://fabricmc.net/versions.html?&version=1.16.5
