### ISSUE TITLE
Gradle build failure

### ISSUE THREAD

**Issue by Plaban-Kumar-Mondal** [FabricMC/fabric-example-mod#118]
```
Build file 'G:\Fabric Projects\Testing Entities\build.gradle' line: 2

An exception occurred applying plugin request [id: 'fabric-loom', version: '0.8-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Java (8). Java 16 or higher is required.
     You can change the Java version in the Gradle settings dialog.

```

I do have these `sourceCompatibility = JavaVersion.VERSION_16` 
`targetCompatibility = JavaVersion.VERSION_16` in my `build.gradle` file and I do have java 16 but I am still getting this error in gradle build. I have cloned this exact project and trying to open it in IntelliJ and facing this issue.

**Comment by NinjaPhenix** [comment]
> You can change the Java version in the Gradle settings dialog.


Make sure intellij is configured to use your project sdk or java 16 for running gradle:
![image](https://user-images.githubusercontent.com/5214513/127035785-69e745bf-1301-4e49-ab67-8420ad53b734.png)
