### ISSUE TITLE
cant generate minecraft and fabric loader src

### ISSUE THREAD

**Issue by Coderx-Gamer** [FabricMC/fabric-example-mod#119]
when i type gradlew genSources in the terminal it takes about 15 seconds and does nothing

**Comment by PTOM76** [comment]
me too.
Log: https://pastebin.com/uRLQYtns
_/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ 
It may be different from the poster, but my development environment is as follows.
Minecraft Version:1.16.5
OS:Windows 10 64bit
Java:8
_/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/ _/

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
