### ISSUE TITLE
Spaces in assetIndex name handled incorrectly

### ISSUE THREAD

**Issue by max-kamps** [FabricMC/fabric-example-mod#12]
When generating the IDEA run configuration, the `assetIndex` inside the client command line is not properly quoted
` --assetIndex 1.14 Pre-Release 1-1.14 --assetsDir "[...]/fabric-loom/assets"` 

Instead, it should be
` --assetIndex "1.14 Pre-Release 1-1.14" --assetsDir "[...]/fabric-loom/assets"` 

This error makes the game unable to find the assetIndex when it contains spaces.

**Comment by modmuss50** [comment]
Nice catch, I will fix within loom here: https://github.com/FabricMC/fabric-loom/blob/36750634ebfbbd658960304c4d09bf2c44b58fde/src/main/java/net/fabricmc/loom/util/RunConfig.java#L154

**Comment by modmuss50** [comment]
Fix rolling out across loom 0.2.1 and 0.2.0
