### ISSUE TITLE
(1.16.5)"gradlew genSources" not working

### ISSUE THREAD

**Issue by PTOM76** [FabricMC/fabric-example-mod#120]
Example Mod: https://github.com/FabricMC/fabric-example-mod/tree/master
I downloaded this and ran "gradlew genSources" but it fails.
Log: https://pastebin.com/HYz8rueJ
How can it be cured?

Minecraft: 1.16.5
Java: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OS: Windows 10 64Bit amd64
Gradle: Gradle 7.0.2

**Comment by modmuss50** [comment]
This is a bug in gradle when running on FAT file systems. It has been fixed in 7.2-rc1, you can edit this in `gradle/wrapper/gradle-wrapper.properties`

**Comment by PTOM76** [comment]
thank you. solved.
