### ISSUE TITLE
(1.18 experimental snapshots) gradlew genSources not working

### ISSUE THREAD

**Issue by JuniorJedi490** [FabricMC/fabric-example-mod#122]
It appears that it can't find the Minecraft version.

The output is as follows:

-------
\* What went wrong:
A problem occurred configuring root project 'fabric-example-mod-1-18-exp-3'.
\> Failed to notify project evaluation listener.
   \> Failed to provide com.mojang:minecraft:1.18_experimental-snapshot-3 : java.lang.RuntimeException: Failed to find minecraft version: 1.18_experimental-snapshot-3
   \> Cannot invoke "net.fabricmc.loom.configuration.providers.minecraft.MinecraftMappedProvider.getMappedJar()" because "mappingsProvider.mappedProvider" is null

\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

\* Get more help at https://help.gradle.org

------
This issue occurs with experimental snapshots 2 and 3; I haven't tried experimental snapshot 1.

**Comment by Technici4n** [comment]
Probably better suited as a loom issue, and I suspect this has been resolved since then.
