### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by NormallyDraco** [FabricMC/fabric-example-mod#128]
I'm running version 1.16.2 and I've already edited the properties to run 1.16.2 yet it keeps telling me to install 1.17 and I am so confused some help would be greatly appreciated [https://i.imgur.com/7owrHdl.png](url)

**Comment by haykam821** [comment]
You must edit `src/main/resources/fabric.mod.json` to change the versions of Minecraft that the mod will load on. The values in `gradle.properties` only control how the mod is compiled.
