### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by Cruii** [FabricMC/fabric-example-mod#13]
Caused by: java.util.zip.ZipError: zip END header not found，When I use IntelliJ IDEA

**Comment by liach** [comment]
How are you using the example mod?

**Comment by Cruii** [comment]
Clone this repo use  IntelliJ IDEA, and use `gradlew idea`.

**Comment by liach** [comment]
try cloning in git terminal again? Remember to use vpn.

**Comment by Cruii** [comment]
C:\Users\Chen Rui>git clone git@github.com:FabricMC/fabric-example-mod.git
Cloning into 'fabric-example-mod'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 209 (delta 15), reused 26 (delta 7), pack-reused 169 eceiving objects:  82% (172/209), 116.01 KiB | 16.00 KiB/s
Receiving objects: 100% (209/209), 126.39 KiB | 18.00 KiB/s, done.
Resolving deltas: 100% (90/90), done.

C:\Users\Chen Rui>cd fabric-example-mod

C:\Users\Chen Rui\fabric-example-mod>gradlew idea

> Configure project :
Fabric Loom: 0.2.2-SNAPSHOT Build(jenkins #11)
:setting up loom dependencies
:merging jars

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fabric-example-mod'.
> Failed to notify project evaluation listener.
   > zip END header not found
   > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s

**Comment by liach** [comment]
Do `./gradlew clean`, and then run `./gradlew genSources idea -S -i > log.txt` and then post the produced log.txt file if the build failed.

**Comment by Cruii** [comment]
Initialized native services in: E:\Environments\GradleRepo\native
Found daemon DaemonInfo{pid=12988, address=[f16123b5-d4af-42c1-b271-f0aa914325dc port:52974, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1557719040181, context=DefaultDaemonContext[uid=e9d01bb3-61c0-49a2-adc2-cddac998e446,javaHome=E:\Environments\JDK,daemonRegistryDir=E:\Environments\GradleRepo\daemon,pid=12988,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} however its context does not match the desired criteria.
At least one daemon option is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=E:\Environments\JDK,daemonRegistryDir=E:\Environments\GradleRepo\daemon,pid=1852,idleTimeout=null,daemonOpts=-Xmx1G,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]
Actual: DefaultDaemonContext[uid=e9d01bb3-61c0-49a2-adc2-cddac998e446,javaHome=E:\Environments\JDK,daemonRegistryDir=E:\Environments\GradleRepo\daemon,pid=12988,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 1988). The daemon log file: E:\Environments\GradleRepo\daemon\4.10.3\daemon-1988.out.log
Starting 7th build in daemon [uptime: 48 mins 29.478 secs, performance: 100%, no major garbage collections]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'C:\Users\Chen Rui\fabric-example-mod\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\Chen Rui\fabric-example-mod\build.gradle'.
Included projects: [root project 'fabric-example-mod']

> Configure project :
Evaluating root project 'fabric-example-mod' using build file 'C:\Users\Chen Rui\fabric-example-mod\build.gradle'.
Fabric Loom: 0.2.2-SNAPSHOT Build(jenkins #11)
:setting up loom dependencies
'E:\Environments\GradleRepo\caches\fabric-loom\version_manifest.json' Not Modified, skipping.
'E:\Environments\GradleRepo\caches\fabric-loom\minecraft-1.14-info.json' Not Modified, skipping.
'E:\Environments\GradleRepo\caches\fabric-loom\minecraft-1.14-client.jar' Not Modified, skipping.
'E:\Environments\GradleRepo\caches\fabric-loom\minecraft-1.14-server.jar' Not Modified, skipping.
:merging jars

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by liach** [comment]
Don't see anything wrong in your log. Try `./gradlew idea --scan` and post the build scan?

**Comment by Cruii** [comment]
https://scans.gradle.com/s/nl5uqfqeggskk
