### ISSUE TITLE
You are using an outdated version of Java (11). Java 16 or higher is required.

### ISSUE THREAD

**Issue by Grayseon** [FabricMC/fabric-example-mod#130]
I am getting this error when playtesting my mod in visual studio code:
You are using an outdated version of Java (11). Java 16 or higher is required.

I am using Java 16 for the language server but it is still giving me this error. Please help!

**Comment by Grayseon** [comment]
Hi, thank you for the reply. Where do I find this?

**Comment by intact** [comment]
Preferences / Settings and search `java home` there
