### ISSUE TITLE
Failed to provide com.mojang:minecraft:1.17.1 : Unsupported class file major version 60

### ISSUE THREAD

**Issue by The-Code-Monkey** [FabricMC/fabric-example-mod#143]
I'm trying to update my 1.16 mod to 1.17 and I keep getting this issue what does it mean can't seem to find any info on what it is trying to say.

```
Failed to provide com.mojang:minecraft:1.17.1 : Unsupported class file major version 60
```

**Comment by apple502j** [comment]
This happens when your Java is too old (e.g. using Java 8 when Java 16 is required, which is the case for 1.17; 1.18 requires Java 17). Try installing Java 17. To download: https://adoptium.net/

**Comment by The-Code-Monkey** [comment]
Ah that makes sense, has anything else major changed as since fixing that I have issue on my GitHub action to do with nbt tags??

**Comment by apple502j** [comment]
There are major changes to many code paths, so I'd recommend checking the relevant source code of 1.16 and 1.17 and comparing those.
