### ISSUE TITLE
Exception has occurred: java.lang.RuntimeException "java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed"

### ISSUE THREAD

**Issue by Sphere107** [FabricMC/fabric-example-mod#149]
I'm using Visual Virtual Studio and I keep getting this error when attempting to launch the Minecraft client and I can't figure out how to fix it.  

RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br/>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:600)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)<br/>at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)</html>
MixinApplyError: Mixin [rubyore.mixins.json:sphere.ruby.ore.rubyore] from phase [DEFAULT] in config [rubyore.mixins.json] from mod [rubyore] FAILED during PREPARE
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)<br/>... 7 more</html>
ClassNotFoundException: The specified mixin 'sphere.ruby.ore.mixins.sphere.ruby.ore.rubyore' was not found
<html>at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)<br/>at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858)<br/>at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)<br/>at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)<br/>... 13 more</html>

**Comment by Baseng0815** [comment]
same here

**Comment by Linguardium** [comment]
you specified a mixin in your mixins.json that doesnt exist in the package/place you told it it existed.

either your rubyore.mixins.json file is wrong (package or classname, case is sensitive) or your mixin class's java file is in the wrong place

**Comment by HurricaneInteractive** [comment]
@Sphere107 Check out [this comment](https://github.com/FabricMC/fabric-example-mod/issues/171#issuecomment-1085527381), it might help you in the right direction if you're still stuck.

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
