### ISSUE TITLE
I'm trying to run the example-mod (Fabric 1.17.1) but I'm getting the following error

### ISSUE THREAD

**Issue by KetoGSDev** [FabricMC/fabric-example-mod#155]
I'm very new to fabric modding and I'm trying to run the example-mod for 1.17.1with the following exception:

```
Did not add data to jar manifest in C:\Users\KetoGS\Desktop\Mods\Hello world!\hello-world-1.17.1\.gradle\loom-cache\1.17.1\net.fabricmc.yarn.1_17_1.1.17.1+build.65-v2\minecraft-project-@-mapped.jar
```

I haven't modified anything except the gradle.properties but NOT the Fabric properties nor the dependencies, here's gradle.properties:

```
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Users/KetoGS/.jdks/openjdk-17.0.1

# Fabric Properties
    # check these on https://fabricmc.net/versions.html
    minecraft_version=1.17.1
    yarn_mappings=1.17.1+build.65
    loader_version=0.12.12

# Mod Properties
    mod_version = 1.17.1-1.0.0
    maven_group = me.ketogs
    archives_base_name = hello-world

# Dependencies
    fabric_version=0.44.0+1.17
```

Also loom version is set to: `0.10-SNAPSHOT`

And here's a more complete crash report: https://pastebin.com/znfgQ12p

Please let me know if you know how to fix this and thank you in advance.

**Comment by ttvWhyteMist** [comment]
the `mod_version` does not include the Minecraft version at any point. you should have it say `mod_version = 1.0.0`. The mod version is picking up two different sets of information and I'm pretty sure that's what's causing the issue. Let me know if this helps!

**Comment by ttvWhyteMist** [comment]
> the `mod_version` does not include the Minecraft version at any point. you should have it say `mod_version = 1.0.0`. The mod version is picking up two different sets of information and I'm pretty sure that's what's causing the issue. Let me know if this helps!

I'm not familiar with the settings for 1.17.1, but if you need the information provided, go to this website:
https://modmuss50.me/fabric.html

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
