### ISSUE TITLE
I Am New to This

### ISSUE THREAD

**Issue by prodigyforever** [FabricMC/fabric-example-mod#156]
Not even gonna pretend to know what's up. I've never even made an issue thing before so I don't know if this is the right place to ask.
I don't know the proper etiquette for this either so if you'd like to educate me or guide to the correct place, I would be greatful. 
So... my computer is a bit of a mess with my paths and registry so if anyone can explain what could be causing this that would be great.

this is in the setup of fabric I have not done anything except

----------------------------------------------------------------------------------------------------------------------------------

The supplied phased action failed with an exception.
A problem occurred configuring root project 'fabric-example-mod'.
Build file 'C:\dev\Minecraft\VRcraft\fabric-example-mod\build.gradle' line: 2
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.10-SNAPSHOT']
Failed to apply plugin 'fabric-loom'.
You are using an outdated version of Java (11). Java 16 or higher is required.
The JAVA_HOME environment variable is currently set to (C:\Program Files\Java\jdk-17.0.2).

----------------------------------------------------------------------------------------------------------------------------------

from my understanding the problem is with the build configuration

I'm currently working in visual studio code, i followed the fabric wiki for setting up VSCode. I checked my Path Enviorment Variables in windows.

**Comment by GersomR-afk** [comment]
Set your JDK to java 16 instead of 11, it should work.

**Comment by Giggitybyte** [comment]
For real-time help, join the Fabric Discord: https://discord.gg/v6v4pMv

**Comment by Miloszp22** [comment]
Have you tried updating Java or using 1.18 template?

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
