### ISSUE TITLE
fabric version.html 22w03a   Wrong version of fabric API

### ISSUE THREAD

**Issue by baka4n** [FabricMC/fabric-example-mod#161]
https://fabricmc.net/versions.html?&version=22w03a
`Wrong version

minecraft_version=22w03a
yarn_mappings=22w03a+build.8
loader_version=0.12.12

#Fabric api
fabric_version=0.28.5+1.15 <--------this

`
actual
`
minecraft_version=22w03a
yarn_mappings=22w03a+build.8
loader_version=0.12.12

#Fabric api
fabric_version=0.46.2+1.18
`

**Comment by modmuss50** [comment]
That website is outdated, please visit the new website https://fabricmc.net/develop/ there is a link provided on the top of the old website. I may setup an auto redirect soon.
