### ISSUE TITLE
genSources gradle task not working

### ISSUE THREAD

**Issue by pete-the-dev** [FabricMC/fabric-example-mod#165]
I have unpacked the example mod and configured the files as directed on the fabric wiki setup page. I am doing this on google cloud shell which is a linux/debian environment. I enter the directory and type the command "./gradlew genSources" and the gradle daemon starts and finishes with a "BUILD SUCCESSFUL" message. There are no sources under the /src directory, even after logging out and back in again. I have tried this many different ways with still no success. Please help?

**Comment by altrisi** [comment]
The src directory is for your mod's sources, genSources creates the minecraft sources for you to be able to browse them with javadoc and everything in your IDE.

**Comment by pete-the-dev** [comment]
Where would the sources be then?
