### ISSUE TITLE
Can’t download

### ISSUE THREAD

**Issue by Foxsamurai** [FabricMC/fabric-example-mod#169]
I saw a tutorial for coding and it told me to download this but I can’t download it, there’s not even a button to do so

**Comment by Linguardium** [comment]
Best method is to use the "Use Template" button to make your own github method. Alternatively, click Code->Download Zip from the Code <> tab to just download the source code.

If you dont know how to use git, i would recommend you learn, it can be very helpful with commit and reversions at a minimum.

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
