### ISSUE TITLE
Installed java version is 17, but gradle thinks it's 11

### ISSUE THREAD

**Issue by TheAwesome98-Real** [FabricMC/fabric-example-mod#185]
When I try compiling, gradle tells me:
`You are using an outdated version of Java (11). Java 17 or higher is required.`
If I run `java --version` in Terminal:
```
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```
I'm using VS Code, and did follow the VS Code setup instructions.

**Comment by modmuss50** [comment]
Make sure your JAVA_HOME environment varible is set correctly.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
