### ISSUE TITLE
[1.19] Could not remap fabric-content-registries-v0-3.1.0+4a3ec384a9-sources.jar fully!

### ISSUE THREAD

**Issue by Raft08** [FabricMC/fabric-example-mod#187]
Hello! 

I'm trying to create a mod project in 1.19 but i always get the same issue when i try to load the example mod in IntelliJ (Ultimate).
I always get this [error (Download)](https://github.com/FabricMC/fabric-example-mod/files/8912497/error.txt)
Here is my gradle.propreties

```
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    minecraft_version=1.19
    yarn_mappings=1.19+build.1
    loader_version=0.14.6

# Mod Properties
    mod_version=1.0.0-ALPHA
    maven_group=be.raft
    archives_base_name=tgc

# Dependencies
    fabric_version=0.55.1+1.19
```

What is the issue?

**Comment by Raft08** [comment]
PS: I already reported this to the Discord Server but they tried to help me but it didn't work :/

So i hope you can help me!

**Comment by warjort** [comment]
If you want help you should post on the discussions tab or discord where you will get more visibility.
If you think its a bug  post it on the fabric-loom project (fabric's gradle plugin that is doing the work here). https://github.com/FabricMC/fabric-loom

However:

> Caused by: java.nio.file.NoSuchFileException: C:\Users\thera\Desktop\Dev\The GreatCraft\Workspace\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_19_1_19_build_4_v2\net\fabricmc\fabric-api\fabric-data-generation-api-v1\5.0.1+2a5b9210a9\fabric-data-generation-api-v1-5.0.1+2a5b9210a9-sources.jar
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:177)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)

I would guess this might be related to the space character in your "The GreatCraft"?
This usually causes problems when tools don't escape it properly for urls, i.e. space -> %20
The other usual cause is windows/FATx not being case sensitive in file names, while java is. 
So make sure you've typed the right case in any configuration, e.g. is it workspace or Workspace?

**Comment by Raft08** [comment]
I actually updated to windows 11 and it fixed this, but thanks!
