### ISSUE TITLE
build.gradle java version error when running

### ISSUE THREAD

**Issue by lolhol** [FabricMC/fabric-example-mod#192]
how 2 fix?

```
Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4-bin.zip'.
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'brigero-muds'.
A problem occurred configuring root project 'brigero-muds'.
Build file 'C:\Users\kk\Downloads\fabric\brigero-muds\build.gradle' line: 2
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.12-SNAPSHOT']
Failed to apply plugin 'fabric-loom'.
You are using an outdated version of Java (8). Java 17 or higher is required.
The JAVA_HOME environment variable is currently set to (C:\Program Files\Java\jdk-17.0.3.1).
```
![Screenshot (185)](https://user-images.githubusercontent.com/62488289/179388085-a3084b53-41ad-4e81-b64d-af01c54477c4.png)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
