### ISSUE TITLE
How should I edit build.gradle when I have deobfuscationed minecraft jar file?

### ISSUE THREAD

**Issue by TanChenyu** [FabricMC/fabric-example-mod#193]

**Comment by TanChenyu** [comment]
@FabricMC

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
