### ISSUE TITLE
Failed to provide com.mojang:minecraft:1.16.5 : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by TanChenyu** [FabricMC/fabric-example-mod#196]
What went wrong about minecraft source?

**Comment by Linguardium** [comment]
this is not a fabric example mod issue.

this is saying some json file was supposed to start with `{` but for some reason it didnt (likely corrupt file or someone edited something wrong)

I suggest joining the discord for support https://discord.gg/v6v4pMv

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
