### ISSUE TITLE
downloadAssets failed 

### ISSUE THREAD

**Issue by Moobusy** [FabricMC/fabric-example-mod#20]
**ENV:** win10, java1.8.0
**Location:**  china

**Step:**  
I tried two ways and got same error.
1>
    1. git clone
    2. ./gradlew.bat downloadAssets
2> 
    1. git clone
    2. ./gradlew.bat genSources
    3. ./gradlew.bat idea

**Tips:**
the error msg said can't find "http://resources.download.minecraft.net/bd/bdf48ef6b5d0d23bbb02e17d04865216179f510a"
, but I can open this link and download it by "wget" or "Chrome" or any other browser   

**Trace:**
Task has not declared any outputs despite executing actions.
16:53:07.313 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':downloadAssets'.
16:53:07.313 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute downloadAssets for :downloadAssets' started
16:53:07.317 [LIFECYCLE] [org.gradle.api.Project] :downloading assets...
16:53:07.317 [DEBUG] [org.gradle.api.Project] :downloading asset icons/icon_16x16.png
16:53:07.392 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@79f7a1e16 pairs: {GET http://resources.download.minecraft.net/bd/bdf48ef6b5d0d23bbb02e17d04865216179f510a HTTP/1.1: null}{Accept-Encoding: gzip}{User-Agent: Java/1.8.0_192}{Host: resources.download.minecraft.net}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Proxy-Connection: keep-alive}
16:53:07.468 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@296988f87 pairs: {null: HTTP/1.1 404 Not Found}{Server: WeCloud-Engine#11/1.16.0}{Date: Fri, 26 Jul 2019 08:53:01 GMT}{Content-Type: text/html}{Content-Length: 165}{Connection: keep-alive}{Keep-Alive: timeout=20}
16:53:07.468 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute downloadAssets for :downloadAssets'
16:53:07.468 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute downloadAssets for :downloadAssets' completed
16:53:07.469 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
16:53:07.469 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':downloadAssets'
16:53:07.469 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :downloadAssets'
16:53:07.469 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :downloadAssets' completed
16:53:07.469 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :downloadAssets (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.158 secs.
16:53:07.469 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 6: released lock on :
16:53:07.469 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.19 completed (1 worker(s) in use)
16:53:07.469 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 6: released lock on root.1.19
16:53:07.469 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 6,5,main]] finished, busy: 0.158 secs, idle: 0.0 secs
16:53:07.469 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 0.0 secs, idle: 0.158 secs
16:53:07.469 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 0.158 secs
16:53:07.470 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 0.158 secs
16:53:07.470 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 0.175 secs
16:53:07.470 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
16:53:07.470 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':downloadAssets'.
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.io.IOException: Not Found
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:53:07.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
16:53:07.472 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings
16:53:07.472 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
16:53:07.472 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 4s

**Comment by modmuss50** [comment]
Closing as its a support issue, and old.
