### ISSUE TITLE
Fabric build failed

### ISSUE THREAD

**Issue by Minecraft200910** [FabricMC/fabric-example-mod#201]
Loom display: unable to pull item

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
