### ISSUE TITLE
[Request] Include MC default folder structure

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric-example-mod#203]
Assets
> modid >
>> blockstates
>> lang
>> models>
>>> block
>>> item
>> textures >
>>> block
>>> item

Data
> modid >
>> loot_tables
>> recipes
>> tags >
>>> items
>>> blocks

These form the basis for the majority of mods and would save me ~5 minutes creating these each time :)

**Comment by xanthian** [comment]
If I pr this change is it likely to be accepted?

**Comment by modmuss50** [comment]
I dont believe you can commit empty folders to git. And im not sure this is something we would want in the example mod tbh.

**Comment by xanthian** [comment]
fair enough, just saves a bit of time setting it up as most mods will use them folders.
