### ISSUE TITLE
[Request] Include MC default folder structure

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric-example-mod#204]
Assets
> modid >
>> blockstates
>> lang
>> models>
>>> block
>>> item
>> textures >
>>> block
>>> item

Data
> modid >
>> loot_tables
>> recipes
>> tags >
>>> item
>>> block

These form the basis for the majority of mods and would save me ~5 minutes creating these each time :)

**Comment by Juuxel** [comment]
Duplicate of #203.

**Comment by xanthian** [comment]
sorry, browser went wonky :)
