### ISSUE TITLE
[Help Wanted | Weird]: maven.fabricmc.net is not reachable from certain ip

### ISSUE THREAD

**Issue by mkikets99** [FabricMC/fabric-example-mod#206]
Website is not down, but i cant download any file from it while i am on `193.239.234.170`
When using VPN, everything good
fabric.net is working. It is only with maven

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
