### ISSUE TITLE
Cannot resolve resource filtering of MatchingCopyAction. IDEA may fail to build project. Consider using delegated build (enabled by default).

### ISSUE THREAD

**Issue by zwl1619** [FabricMC/fabric-example-mod#209]
There is an error:
![Snipaste_2022-09-24_10-37-25](https://user-images.githubusercontent.com/13177997/192076630-fd5dd0f1-8600-45ae-a2d3-d3ee41c6b9f7.png)
What should I do?

**Comment by modmuss50** [comment]
You can ingore this warning, its a known intelij bug: https://youtrack.jetbrains.com/issue/IDEA-296490

**Comment by VacantHusky** [comment]
OH NO！It's just sending chat messages

**Comment by SolidBlock-cn** [comment]
The issue seems to have continued for one year without being fixed.
