### ISSUE TITLE
I keep getting this error no matter what

### ISSUE THREAD

**Issue by Glitch4556** [FabricMC/fabric-example-mod#212]
./gradlew genSources                                    
Starting a Gradle Daemon, 4 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Configure project :
Fabric Loom: 1.0.11

> Task :genSourcesWithCfr FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':genSourcesWithCfr'.
> There was a failure while executing work items
   > A failure occurred while executing net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction
      > Failed to decompile

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 33s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by Juuxel** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
