### ISSUE TITLE
GitHub build script should be updated

### ISSUE THREAD

**Issue by Madis0** [FabricMC/fabric-example-mod#214]
Current one gives those errors:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, gradle/wrapper-validation-action, actions/setup-java, actions/upload-artifact, actions/setup-java, actions/checkout

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![image](https://user-images.githubusercontent.com/8611110/197361966-9b586dd8-d56b-4de5-ae59-0595014497a1.png)

**Comment by toomuchcodehelp** [comment]
not to mention that windows builds are kind of unnecessary. That being said, theses commands probably won't be gone for a long time.
