### ISSUE TITLE
Vulkan API and FidelityFX Super Resolution (Performance x2)

### ISSUE THREAD

**Issue by LiberteIV** [FabricMC/fabric-example-mod#217]
Hello,

I'm here to mention this mod https://github.com/xCollateral/VulkanMod which allows to start minecraft with the Vulkan API instead of OpenGL, chances are if the mod get's enough attention.. it might support **F**idelityFX **S**uper **R**esolution which will drastically improve performance.
As an example this mod https://www.nexusmods.com/aplaguetalerequiem/mods/9 replaces DLSS with FSR in A Plague Tale Requiem, without the mod i had an average of 40 FPS on a GTX 1080 Ti 1440p ultra settings. With the FSR mod on Quality mode i had an average 80 FPS with the same settings while the image still looked even better then native.
Those results are crazy.
I beleve this (DLSS and FSR) are the future and will be supported by all major upcomming games.
The potential is to much to be ignored, my opinion.

Taking a look at VulkanMod's github page it clearly says this: **"This is a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API."**
With 12,163 downloads the mod is still pretty smal compared to fabric / optifine / sodium, then again **imagine what Fabric, VulkanAPI, Optifine, and FidelityFX Super Resolution could do together**, i have no doubt minecraft's performance would skyrocket.

Seus Shader and Patrix Resourcepack are very performance hungry, getting an average 60 FPS with both enabled, i consider them both mandatory for playing minecraft as they look really good.
**With Vulkan and FSR those 60 FPS could easily turn into 120.**
At this moment using optifine with fabric requires optifabric, combining those mods with vulkanmod results in a game-crash.
By creating this "issue" i hope to bring more attention to the vulkanmod and it's potential for FSR.
If fabric, optifine, and optifabric would officialy support vulkanmod...

![Seus PTGI + Patrix](https://user-images.githubusercontent.com/116210112/198883305-850e9c2b-9e8e-46c4-b0ce-cad73a498a42.png)

![Dragons](https://user-images.githubusercontent.com/116210112/198883325-c33fed27-f6cb-4885-9941-d53a99c82938.png)

![Survival House](https://user-images.githubusercontent.com/116210112/198883329-8b90d341-ace4-48f1-a192-7ba61ba10103.png)

![Argonath LOTR](https://user-images.githubusercontent.com/116210112/198883332-ef2c4fb3-270d-4bd3-9c30-c628fca60e15.png)

**Comment by Juuxel** [comment]
This isn't relevant to the example mod.

**Comment by LiberteIV** [comment]
> This isn't relevant to the example mod.

I wasn't sure where to post it because there is multiple fabric sections on github, this is the one i was directed to from the official fabric website/sourceforge website. Posting there now.
