### ISSUE TITLE
How to add redstone status to a square

### ISSUE THREAD

**Issue by alazeprt** [FabricMC/fabric-example-mod#218]
I want my square to change a picture when it detects a red stone signal. How can I add a red stone signal detection?

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
