### ISSUE TITLE
genSources not fully working

### ISSUE THREAD

**Issue by AnnoyingB** [FabricMC/fabric-example-mod#225]
I am not sure if this is a problem with fabric but when I run ```gradle genSources```, after a while it was blocked as it was trying to hijack another app? I don't know if it is a problem with my antivirus or gradle/fabric.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
