### ISSUE TITLE
build fail loom cache

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric-example-mod#230]
![erro](https://user-images.githubusercontent.com/106870098/215272967-819f9731-f64b-4300-aae2-b9cc26023aa8.png)
heres the error it worked once i modded the gradle to use minecrafts java so the error text is normal about java

**Comment by modmuss50** [comment]
This warning is shown when the previous build failed, so loom is regenerating all of the files to ensure they arent not in a corupt state. There is no error shown here.
