### ISSUE TITLE
Gradle loom cache error deleted both folders

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric-example-mod#231]
![CC5003CA-9CF3-4A81-9F17-B1E44FCE164C](https://user-images.githubusercontent.com/106870098/215279704-f04937e7-520c-4d43-960f-f43bb6c5c5c1.png)
I deleted both local .gradle folder and the one in my user account it’s not a failed build
Like you told me @modmuss50
It fails that every time

**Comment by modmuss50** [comment]
Please dont create a new issue, with the same screenshot. After a successful build this warning will go away.

**Comment by Danjhop4** [comment]
It will not build even when I clear all data in both folders

**Comment by Danjhop4** [comment]
It just fails to fix

**Comment by modmuss50** [comment]
Can you show the error please?

**Comment by Danjhop4** [comment]
It’s the picture I sent that’s all gradle shows it’s a print screen

**Comment by Danjhop4** [comment]
I run gradle from the bat file so it ends as soon as it’s done

**Comment by Danjhop4** [comment]
I had to catch it before it finished

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
