### ISSUE TITLE
I would love to make a 1.19.2 mod but i cant download it

### ISSUE THREAD

**Issue by kaidacoder** [FabricMC/fabric-example-mod#236]
please help me

**Comment by Xanderplayz16** [comment]
https://www.mediafire.com/file/zpoo8z513vdu39h/2023-02-04_13-57-56.mp4/file
Thank me

**Comment by kaidacoder** [comment]
thanks

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
