### ISSUE TITLE
Where would you find the title screen code in fabric 1.19.2

### ISSUE THREAD

**Issue by kaidacoder** [FabricMC/fabric-example-mod#239]
I need help to find the file that contains the minecraft title screen code

**Comment by haykam821** [comment]
To answer your question, `TitleScreen` contains the title screen code in Yarn mappings. However, this is not the correct place to ask these questions. You should ask in discussions instead.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
