### ISSUE TITLE
Fix VSCode support in .gitignore

### ISSUE THREAD

**Issue by NatoBoram** [FabricMC/fabric-example-mod#24]
The current `.gitignore` for VSCode is this : 

```gitignore
# vscode

.settings/
.vscode/
bin/
.classpath
.project
```

While in reality, it should be that : 

```gitignore
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

You can view proper templates for `.gitignore` in [github.com/github/gitignore](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore).

A useful tool to generate `.gitignore` can be found at [gitignore.io](https://www.gitignore.io/?templates=java,linux,macos,gradle,windows,visualstudiocode). Personally, I love this tool. I'm not a fan of having to look for each individual `.gitignore` for every project I create, I'm way too lazy for that.

The `.classpath`, `.project`, `.settings` and `.factorypath` are added by [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) inside `.vscode/settings.json`. Well, they should probably be also inside `.gitignore`, but I think that they should be in a separate "block" from VSCode.

**Comment by modmuss50** [comment]
Im not sure this is fully correct. The launch jsons change based on the system they are being ran as. Possibly just ingoring the `launch.json` would be a solution.

**Comment by NatoBoram** [comment]
If the project maintainer wants to share a specific launch config with the users of this project, then it's there.

Here's more insight from someone working directly on VSCode : https://stackoverflow.com/a/32979933/5083247

**Comment by modmuss50** [comment]
Fabrics launch files will not translate across systems, if a project specific run arg needs to be added it should be done through gradle. If the ability to do that doesn’t exist open a loom issue

**Comment by modmuss50** [comment]
This is still correct, you should have a fresh set of launch configs for each machine.
