### ISSUE TITLE
Downloading always fails

### ISSUE THREAD

**Issue by Luxvao** [FabricMC/fabric-example-mod#241]
I don't know if this is an issue with the example mod, or if it's an issue with my connection, but no matter what I do, downloading assets always fails. Can someone please help me, I'm new.

**Comment by CommanderGL** [comment]
Are you talking about "./gradlew genSources"? If so I have same issue (Posted on Reddit).

https://www.reddit.com/r/fabricmc/comments/11dy0hz/cant_use_gradlew_gensources_on_raspberry_pi_4/

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
