### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Loutto** [FabricMC/fabric-example-mod#247]
How do I turn off The option "Always" when it asks if I need to "Always" open the  gradle.properties on chrome?
Because now there is No way to fix it. I can't go on NotePad for gradle.properties

**Comment by muhammedesadcomert** [comment]
> How do I turn off The option "Always" when it asks if I need to "Always" open the gradle.properties on chrome? Because now there is No way to fix it. I can't go on NotePad for gradle.properties

Start > Settings > Apps > Default apps > Choose default by file type.

_Note for @Loutto: This issue not about this repository. You need make sure the issue is about it when opening._
![image](https://user-images.githubusercontent.com/46245749/230736781-6fffd51c-38c5-452c-9221-2721878703a5.png)

**Comment by muhammedesadcomert** [comment]
Issue can be closed.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
