### ISSUE TITLE
Cause: zip END header not found

### ISSUE THREAD

**Issue by Almazoioio** [FabricMC/fabric-example-mod#256]
When i'm triyng to setup fabric-project this error occures (Same for fabric template mod generator)
![Error](https://github.com/FabricMC/fabric-example-mod/assets/122214031/7d143518-e430-4c93-9ab2-e65386cf3933)

**Comment by Almazoioio** [comment]
This strange thing have ruined my previous fabric-project

**Comment by Almazoioio** [comment]
Interesting, i need to mention: 1.19.4 works well, but not 1.20

**Comment by DakotaPride** [comment]
Did you find a solution to this? I'm experiencing the same issue when trying to update my 1.19.2 mod to 1.19.4

**Comment by Almazoioio** [comment]
> Did you find a solution to this? I'm experiencing the same issue when trying to update my 1.19.2 mod to 1.19.4

Hello, mhm, no( I have no idea why it happened and how to fix it...

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a discussion thread, or a message on our discord server. Please post your request on one of these, and the conversation can continue there.
