### ISSUE TITLE
Gradle Failure on JDK 21

### ISSUE THREAD

**Issue by MDevVal** [FabricMC/fabric-example-mod#257]
I am currently using Linux 6.1.35-0-lts. However, whenever I try to execute any gradle command in this project using JDK 21, I encounter the following error

```
java.io.StreamCorruptedException: invalid type code: 00
> invalid type code: 00
```

**Comment by MDevVal** [comment]
I am building in a container that only has jdk21 so that issue is not relevant and I am able to build other projects and parts of fabric with jdk21.

**Comment by ElieGonzales** [comment]
I am having the same issue. I have tried using a different SDK, and it changed nothing.

**Comment by modmuss50** [comment]
I dont think there is anything I can do about this, hopefully it will be fixed once Gradle offically support JDK 21
