### ISSUE TITLE
Make it more clear what fabric.mod.json entries should be replaced

### ISSUE THREAD

**Issue by triphora** [FabricMC/fabric-example-mod#258]
Hi there o/ I'm one of the two main reviewers for mods on Modrinth.

Among part of our manual review, we tend to check the fabric.mod.json files to ensure the metadata of the uploaded file matches the metadata an author has entered into Modrinth.

An issue I've come across persistently is that folks will simply leave an entry from the example mod. For example, source/issue links pointing to this repository, or license entries still listed as CC0-1.0.

This is far from ideal, leading to the problem that invalid metadata is a common rejection reason for mods. It causes more time to be wasted for both us, the reviewers, as well as the authors.

What I would like to suggest is to make it more clear what should be changed in the fabric.mod.json. For example, instead of `license` being `CC0-1.0`, it could be `INSERT LICENSE HERE`.

I'm willing to make a PR for this if others agree with this idea.

**Comment by haykam821** [comment]
I think a more effective method to reduce license discrepancy would be to emphasize the mod template generator and enable license customization there. Any license discrepancy with the existing mod template in this repository would come from the fact that users are replacing the license file without updating the metadata, presumably from existing license selectors like the GitHub repository creation flow (...though that should be skipped for templates).

**Comment by Levoment** [comment]
Agreed. From experience, the users would likely leave the text `INSERT LICENSE HERE` text in the json file without changing it.

Adding a license dropdown on https://fabricmc.net/develop/template/ could work to mitigate that. Although only to a certain extent if it adds it only to the json and doesn't add the actual license. While adding and maintaining up to date licenses would be a lot of work, adding only adding the string to the `fabric.mod.json` file in the generator, it would help reduce the discrepancies.

**Comment by triphora** [comment]
In that case this is probably more of a duplicate of FabricMC/fabricmc.net#24. Thanks for the feedback!
