### ISSUE TITLE
The mod built doesnt work

### ISSUE THREAD

**Issue by Shuaiouke** [FabricMC/fabric-example-mod#26]
I change the files acorrding to my need like the modid.json versiobln etc and after I build it, i put it in the mods folder but fabric doesnt read it, I also tried putting the .jar file in my own minecraft instead of the one giving with getSource but it just dont work 😔

**Comment by shedaniel** [comment]
Log of the production environment? Also how did you build the mod?

**Comment by Shuaiouke** [comment]
./gradlew build
and where to find the log?

**Comment by shedaniel** [comment]
I meant the log of the production environment. Which means the log of you running it in official minecraft.

**Comment by Shuaiouke** [comment]
so I put the mod in and launch Minecraft and send that log file here?

**Comment by shedaniel** [comment]
the normal one

**Comment by Shuaiouke** [comment]
ok thanks

**Comment by Shuaiouke** [comment]
[latest.log](https://github.com/FabricMC/fabric-example-mod/files/3488566/latest.log)

**Comment by Shuaiouke** [comment]
I have a few other mods installed but I'm too lazy to remove them

**Comment by Shuaiouke** [comment]
[latest.log](https://github.com/FabricMC/fabric-example-mod/files/3488567/latest.log)
ok file this is the log with other mod removed

**Comment by shedaniel** [comment]
What does your mod look like?

**Comment by Shuaiouke** [comment]
Mod-Name-Version.jar

**Comment by shedaniel** [comment]
Is there a file called fabric.mod.json inside

**Comment by Shuaiouke** [comment]
yes

**Comment by shedaniel** [comment]
bruh don’t just guess, extract them jar and see it for yourself

**Comment by Shuaiouke** [comment]
no

**Comment by shedaniel** [comment]
That’s the issue, fabric only loads jars with fabric.mod.json

**Comment by Shuaiouke** [comment]
I see and fabric.mixin.json?

**Comment by shedaniel** [comment]
find help at fabric discord, it is easier. This is only the issue tracker, it is only for you to report bugs.

**Comment by Shuaiouke** [comment]
where do I join?

**Comment by shedaniel** [comment]
https://discord.gg/v6v4pMv

**Comment by Shuaiouke** [comment]
thanks
