### ISSUE TITLE
Can't import net.minecraft.util.registry

### ISSUE THREAD

**Issue by Soulsender** [FabricMC/fabric-example-mod#260]
I'm unable to import `net.minecraft.util.registry`. I can import `net.minecraft.registry` but not with the utils part. 

I tried regenerating the gradle sources, but that didn't fix it.

There is an error of `Cannot resolve symbol 'registry'`

I'm using minecraft 1.20.1.

My code:

```java
package net.soul.testmod1.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.registry.Registry; // <- this is the issue
import net.minecraft.util.Identifier;
import net.soul.testmod1.TestMod1;


public class ModItems {

    public static final Item TESTITEM = registerItem("testitem", new Item(new FabricItemSettings().group(ItemGroup.MISC)));

    private static Item registerItem(String name, Item item) {
        return Registry.register(Registry.ITEM, new Identifier(TestMod1.MOD_ID, name), item);
    }

    public static void registerModItems() {
        TestMod1.LOGGER.debug("Registering Mod Items for " + TestMod1.MOD_ID);
    }
}
```

**Comment by Cabbasca** [comment]
you need fabric api

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.

**Comment by Soulsender** [comment]
> you need fabric api

I have fabricAPI
