### ISSUE TITLE
Why is there a problem with my idea IDE and I can't create fabric。MC FOREVER

### ISSUE THREAD

**Issue by JerryFuR** [FabricMC/fabric-example-mod#264]
When I create fabric project，my main .java only has " 
 public` class Trymod{
} 
 "and this is my project name(Trymod).also I cant run,please 
 the big guy to solve it.I want keep my Favorite game and Make some effort to contribute. MC FOREVER

**Comment by JerryFuR** [comment]
MC FOREVER

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
