### ISSUE TITLE
Fabric doesn't load in my `.json` file

### ISSUE THREAD

**Issue by Zedespook** [FabricMC/fabric-example-mod#27]
I was trying to add a new item to the mod, I followed the tutorial, and I got to the "texture import" part, where the tutorial tells me to put a `.json` file and a `.png` file to the following folders:

`.../resources/assets/tutorial/models/item/fabric_item.json` <- For the `.json` file
`.../resources/assets/tutorial/textures/item/fabric_item.png` <- For the `.png` file

I've put these two files in the `[MOD FOLDER]/src/main/resources...` (etc.), but when I'm starting the game, the same error message comes up. `[Server-Worker-3/WARN]: Unable to load model: 'hammer:diamond_hammer#inventory' referenced from: hammer:diamond_hammer#inventory: java.io.FileNotFoundException: hammer:models/item/diamond_hammer.json` (Yes, I renamed the workspaces.)

Please, take a look into my issue, because I'm sure it's me messing up, I just don't know what I messed up.

**Comment by modmuss50** [comment]
Closing as its a support issue and old. If you still need help feel free to get help via the dissuction areas linked on the fabric website.
