### ISSUE TITLE
Gradlew Build Issue

### ISSUE THREAD

**Issue by Inexris** [FabricMC/fabric-example-mod#271]
> Configure project :
Fabric Loom: 1.4.5

> Task :genSourcesWithCfr FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':genSourcesWithCfr'.
> GenSources task requires a 64bit JVM to run due to the memory requirements.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
1 actionable task: 1 executed

**Comment by Inexris** [comment]
Please someone help,Im stuck on this error!
My pc's spec:*Windows 10 64bit
                      *8GB ram
Java Applications:*Java runtime 8 64 bit
                            *Termurin 17

**Comment by Linguardium** [comment]
remove all installs of java
install java 17 x64 jdk
set the project sdk to 17 sdk
set the gradle sdk to project sdk

**Comment by Inexris** [comment]
Ok thanks, I will try that

**Comment by Inexris** [comment]
Guess It isn't working yet and Im getting the same error

**Comment by Inexris** [comment]
> GenSources task requires a 64bit JVM to run due to the memory requirements.
But I already had a 64bit JVM?
Pls someone help!

**Comment by Linguardium** [comment]
step 1: remove all installs of java

**Comment by Inexris** [comment]
Already did

**Comment by Inexris** [comment]
I dont want to fix it im swiching to python
