### ISSUE TITLE
 - Mod fabric-object-builders-v0 depends on mod {fabric-mining-levels-v0 @ [*]}, which is missing!

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-example-mod#45]
This error just comes when trying to build the project with pretty much everything the same.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
