### ISSUE TITLE
Example build.gradle uses snapshot version of loom

### ISSUE THREAD

**Issue by immibis** [FabricMC/fabric-example-mod#48]
The example mod's build.gradle has:

```
id 'fabric-loom' version '0.2.7-SNAPSHOT'
```

This seems bad - snapshot versions of Loom should only be used for Loom development.

**Comment by shedaniel** [comment]
There isn't a loom version that is not snapshot

**Comment by immibis** [comment]
Then maybe this should be a Loom bug instead.

**Comment by shedaniel** [comment]
I wouldn't say this is a "bug", but potentially a "small issue"?

**Comment by Prospector** [comment]
it's the current intended way for it to work, though it could be argued that it's not a great way.

**Comment by immibis** [comment]
Potentially having a different version every time you ask for the same version seems like a bug to me. You build your mod and it works, someone else clones your mod and builds it, and it doesn't work for them because something changed in Loom, even though they have the same Loom version.

**Comment by liach** [comment]
Currently loom 0.2.6 has a few problems and 0.2.7 fixes most of those. 0.2.7 isn't unstable.
