### ISSUE TITLE
Changes to .gitignore for VSCode Support

### ISSUE THREAD

**Issue by andybond006** [FabricMC/fabric-example-mod#5]
I talked with @modmuss50 for some time yesterday on Discord about issues using VSCode to run the fabric-example-mod project, which are still not resolved that I can tell - however, while I was attempting to run the project I did notice some things missing from the `.gitignore` file that should be included for all projects if anyone with VSCode decides to open it.

Here are the things I feel should be added to the `.gitignore` file:
```
#vscode

.settings/
.vscode/
bin/
.classpath
.project
```

I found many of these by cloning the project https://github.com/strikerrocker/CraftingStick and then opening the project in VSCode. 

(This project I can run using VSCode whereas I cannot with the example project)

**Comment by NatoBoram** [comment]
I'd like to point out that GitHub has `.gitignore` templates for various languages and editors.

https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore
