### ISSUE TITLE
Attempting to build or run genSources causes Unable to delete file error.

### ISSUE THREAD

**Issue by jpeterik12** [FabricMC/fabric-example-mod#50]
Every time I attempt to build or `genSources`, it says it's unable to delete a file from the .gradle\loom-cache\remapped_mods\ folder, and checking if a process is using it shows java.exe as the culprit. Killing java and running again changes which file it throws an error about. After doing this for a while, I get an error about `File 'C:\Users\<me>\.gradle\caches\fabric-loom\1.15.2-mapped-net.fabricmc.yarn-1.15.2+build.15-v2\minecraft-1.15.2-mapped-net.fabricmc.yarn-1.15.2+build.15-v2-sources.lmap' specified for property 'lineMapFile' does not exist.`
I don't know if this is the right project to submit this issue under, but my goal is just to look at Minecraft's deobfuscated code, and this was the way suggested to me.

**Comment by Rojoss** [comment]
Yeah I have the same issue.
Going back 1 commit fixed the issue for me so this must have broken it.
https://github.com/FabricMC/fabric-example-mod/commit/19fa3a76bce814ece51c8bcdec12771e4c6394a1

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
