### ISSUE TITLE
Trying to make Custom Block copy settings from any Log causes IllegalArgumentException

### ISSUE THREAD

**Issue by P3NG00** [FabricMC/fabric-example-mod#51]
gradle.properties:
minecraft_version=20w18a
yarn_mappings=20w18a+build.14
loader_version=0.8.2+build.194
fabric_version=0.10.3+build.338-1.16

build.gradle
dependencies {
	minecraft "com.mojang:minecraft:20w18a"
	mappings "net.fabricmc: yarn:20w18a+build.14:v2"
	modImplementation "net.fabricmc:fabric-loader:0.8.2+build.194"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.10.3+build.338-1.16"
}

The above are the only things I've changed in my main project files.

A block I made in my mod is supposed to copy the settings from Blocks.OAK_LOG. However, when that block is initialized, it throws an 'IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.util.math.Direction$Axis, values=[x, y, z]} as it does not exist in Block{minecraft:air}." Every other block I try this with works except for Logs. When I change the block to copy to anything else it runs fine. What I mean by 'copy' is when I use the static AbstractBlock.Settings.copy(Block) method.

Hopefully the crash log is attached. I haven't reported anything on GitHub before so if you need any more info relating to this please don't hesitate to ask!
[crash-2020-05-05_21.42.17-client.txt](https://github.com/FabricMC/fabric-example-mod/files/4584719/crash-2020-05-05_21.42.17-client.txt)

**Comment by Prospector** [comment]
Not an issue with fabric-example-mod, nor is it an issue at all. You can only copy the log block's settings to other blocks with an `axis` property, such as a PillarBlock

**Comment by P3NG00** [comment]
> Not an issue with fabric-example-mod, nor is it an issue at all. You can only copy a log block's settings to other blocks with an `axis` property, such as a PillarBlock

Gotcha. Thanks for clarifying!
