### ISSUE TITLE
zip END header not found 

### ISSUE THREAD

**Issue by Olitwee** [FabricMC/fabric-example-mod#52]
I don't have a lot of knowledge I have fixed this issue before but I didn't know how I did it. Please give me instructions, Thanks

**Comment by modmuss50** [comment]
One of your mod jars is most likely corrupted.

**Comment by modmuss50** [comment]
Can you post the whole log?

**Comment by Olitwee** [comment]
Thanks but sadly i deleted all my mods...

**Comment by Olitwee** [comment]
Let me dowload all my mods again

**Comment by Olitwee** [comment]
Case closed i have deleted all mods and installed the mods i needed
