### ISSUE TITLE
Remove Fabric API dependencies

### ISSUE THREAD

**Issue by kvverti** [FabricMC/fabric-example-mod#55]
Remove the `modImplementation` of the full fabric API, and remove `"fabric": "*"` from the example mod's `fabric.mod.json`.

Leaving the fabric API in the example mod means that many mods depend on the full Fabric API, even when they don't use all of API's modules.

This issue is part of [a plan to improve depending on Fabric API](https://gist.github.com/kvverti/3fc6a05d974210f785a9a751d5e0ae28).

**Comment by Pyrofab** [comment]
I think one possibility would be to add commented out dependencies on every existing API module. That way, enabling modules just takes a few keystrokes, and discoverability stays high.

**Comment by i509VCB** [comment]
Until a solution is written up and accepted, I would say no.

**Comment by eehunter** [comment]
@Pyrofab JSON doesn't allow comments.

**Comment by modmuss50** [comment]
No, this repo is to help most people get started, and most people need the API. There is a comment that mentions its not required.
