### ISSUE TITLE
Fatal error on fabric-dimensions-v1 mixin at startup

### ISSUE THREAD

**Issue by Slexom** [FabricMC/fabric-example-mod#61]
Updated to 1.16.2 got an error at startup about a fabric mixin.
Error log: https://gist.github.com/Slexom/988e452f778eb3c2065e697fd37c7ce4

```
minecraft_version=1.16.2
yarn_mappings=1.16.2+build.1
loader_version=0.9.1+build.205 
fabric_version=0.17.2+build.396-1.16
```

**Comment by florensie** [comment]
Another module is pulling in `fabric-dimensions-v1`. It's probably REI. Just update all your other dependencies.

**Comment by Slexom** [comment]
Is in development, updated the dependencies but now the mixin giving error is the biome one
gist: https://gist.github.com/Slexom/a6c5d4f1f4c9521a30f663750999912a

```
dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	compileOnly group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

	modApi "me.shedaniel.cloth:config-2:4.7.0-unstable"
	include "me.shedaniel.cloth:config-2:4.7.0-unstable"
	modApi "me.sargunvohra.mcmods:autoconfig1u:3.2.0-unstable"
	include "me.sargunvohra.mcmods:autoconfig1u:3.2.0-unstable"
	modImplementation "io.github.prospector:modmenu:1.14.6+build.31"
	// PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
	// You may need to force-disable transitiveness on them.
}
```

**Comment by florensie** [comment]
fabric-biomes-v1 should not be loading at all (it was removed for 1.16.2) so something is still pulling it in.

**Comment by Slexom** [comment]
It appear on the external library list, so something add it. I've run cleanLoom task, reimported project, deleted cache.
![image](https://user-images.githubusercontent.com/9221469/89952148-ff698a80-dc2c-11ea-8063-b4bf31b6f4a7.png)

**Comment by Slexom** [comment]
Also cloning the whole repository not helped
