### ISSUE TITLE
Where to download 1 15 2

### ISSUE THREAD

**Issue by Miros77** [FabricMC/fabric-example-mod#64]
![sad](https://user-images.githubusercontent.com/59547044/92397218-1f5a7400-f12f-11ea-9f80-42f918942495.png)

**Comment by ShiraDev** [comment]
https://modmuss50.me/fabric.html

**Comment by DietrichPaul** [comment]
Does it work for you?

**Comment by halotroop2288** [comment]
For users: https://fabricmc.net/use/
For developers: https://fabricmc.net/versions.html?&version=1.15.2
~~Delet this~~ Close this issue now.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
