### ISSUE TITLE
build.gradel and client

### ISSUE THREAD

**Issue by tbnralix** [FabricMC/fabric-example-mod#65]
i am useing vscode. The build.grable file has 39 erers or problomes and when i run the client it saids build faild do you want to continue

**Comment by ShiraDev** [comment]
are you able to upload your build file?

**Comment by DietrichPaul** [comment]
Is it solved?

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
