### ISSUE TITLE
Can you make a forum or add lots of information to the wiki?

### ISSUE THREAD

**Issue by Maxbrick** [FabricMC/fabric-example-mod#66]
There isn't a forum for fabric that i know of, and the wiki has helpful information but it doesnt tell me a lot of things i need to know.
The only thing is the discord but i dont have discord so can you make a forum or something?

**Comment by NeRdTheNed** [comment]
What do you want to know? Asking for more documentation is valid, but it's possible that the wiki already has what you're looking for.

**Comment by Maxbrick** [comment]
Oof sorry for really late respond..
Ok so I want to know how to make blocks do certain things on command (e.g. teleporting the player)
But things like this aren't shown on the wiki, is it in the fabric api? Do i use other apis? how?

Maybe there is stuff on how to do it there but im just not finding it..
Also, can you make like a forum? That would be a lot more helpful, so if it's possible, please do it.

**Comment by YTG1234** [comment]
> Ok so I want to know how to make blocks do certain things on command (e.g. teleporting the player)

what do you mean "on command"? For most cases, you can just look how vanilla does it and do the same (for this one `Entity#teleport` iirc)

> Also, can you make like a forum? That would be a lot more helpful, so if it's possible, please do it.

There was a discussion about that in the discord, and from what I remember the answer is "maybe".

**Comment by YTG1234** [comment]
The wiki doesn't document everything because for most things we'd just use vanilla methods because we don't *need* Fabric API to provide this stuff. I see the wiki as documentation to get started, and documentation for Fabric API stuff. Again, for most things you can look how vanilla does it and do the same.

**Comment by Maxbrick** [comment]
alright then, thanks

**Comment by ByMartrixx** [comment]
To do something when something else happens ("on command" as you said), you have to use events. The event you want may be in the Fabric API, but if it doesn't, you can create your own: https://fabricmc.net/wiki/tutorial:events

**Comment by Maxbrick** [comment]
alright, thanks

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
