### ISSUE TITLE
Minecraft not launching on Debian Linux

### ISSUE THREAD

**Issue by YEEETT** [FabricMC/fabric-example-mod#70]
i cant launch mc
i keep getting this error
(im using eclipse on debian linux)
http://www.hastebin.net/evypoquceb.properties

**Comment by modmuss50** [comment]
Try running `./gradlew downloadAssets`

**Comment by antonilol** [comment]
what is that link...

**Comment by YEEETT** [comment]
> what is that link...

broken because hastebin changed urls
