### ISSUE TITLE
running genSources causes an error where no 'minecraft' dependency is specified

### ISSUE THREAD

**Issue by KeanaGindy** [FabricMC/fabric-example-mod#76]
Everytime I run ./gradlew genSources the build fails and it says that no Minecraft dependency is specified.

**Comment by KeanaGindy** [comment]
I also have this issue:
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-bin.zip'.
Build completed with 2 failures.

**Comment by Calvin-Coding** [comment]
I am getting a similar issue.

Here is some info

![image](https://user-images.githubusercontent.com/60584878/104679949-a0a8b100-56a3-11eb-9f4b-dc215aeac93a.png)


When I try to launch the client, I get the following errors:
The import net.minecraft cannot be resolved
TitleScreen cannot be resolved to a type

These errors are happening in the example mixing file.

Here are the following logs:

[19:45:27] [main/ERROR] (FabricLoader) Could not find valid game provider!
[19:45:27] [main/ERROR] (FabricLoader) - Minecraft

I ran cleanup Loom Binary but I still got the errors.

If someone could help me that would be great,

Thanks

Calvin-Coding

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
