### ISSUE TITLE
JCenter is shutting down on May 1st, it should not be included as a repository by default

### ISSUE THREAD

**Issue by coderbot16** [FabricMC/fabric-example-mod#78]
[Into the Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

By default, every mod created based on the example mod depends on JCenter through `settings.gradle`. While this won't fix existing mods, at the very least we should ensure that new mods created don't depend on it.

**Comment by modmuss50** [comment]
Balls, yes. I didnt know this was here.... It should have never been there in the first place.
