### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by SiniMini876** [FabricMC/fabric-example-mod#83]
![image](https://user-images.githubusercontent.com/67224094/107155231-e8a7b480-697f-11eb-9679-aa4dd2bbcd2f.png)

I followed the instructions from the wiki and typed the command `gradlew genSource` and it gave me an error.
I tried multiple times and even deleting the entire project, it didn't help.
I use IntelliJ as an IDEA

**Comment by YTG1234** [comment]
Can you verify that there's a `gradle-wrapper.jar` in the `gradle\wrapper` folder?

**Comment by SiniMini876** [comment]
Yes

**Comment by SiniMini876** [comment]
I think the problem is in my pc, cause for anyone else its work fine
