### ISSUE TITLE
"gradle runClient" fails: Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by SirEnder125** [FabricMC/fabric-example-mod#88]
Hello. I was following the custom item tutorial, and I had gotten as far as the
build process. When I ran "gradle runClient" it gave me this error:
> Compilation failed; see the compiler error output for details.

I can't find the error output file and I don't know what could be wrong.

JAVA_HOME: C:\Program Files\Amazon Corretto\jdk11.0.10_9

**Comment by SirEnder125** [comment]
Hmmm. After running `gradle --info runClient`,
it says this:
```ExampleMod.java:8: error: cannot find symbol
    public static final Item FABRIC_ITEM = new Item(new FabricItemSettings().group(ItemGroup.MISC));
                        ^
  symbol:   class Item
  location: class ExampleMod```

**Comment by OroArmor** [comment]
it looks like the minecraft dependency isnt loading. make sure it is being remapped

**Comment by SirEnder125** [comment]
Sorry, I am a bit of a noob. Can you please simplify? Sorry.

**Comment by OroArmor** [comment]
delete `~/.gradle/caches/fabric-loom/` then run `gradle runClient --refresh-dependencies`
`~` is the user home so `C:\Users\MyUser\` on windows

**Comment by SirEnder125** [comment]
Okay. I'll try.

**Comment by SirEnder125** [comment]
It did not work. :/

**Comment by SirEnder125** [comment]
Downloaded the template again and now `gradlew eclipse` gives me this error:
> A problem occurred configuring root project 'testmcmod-master'.
> Failed to provide net.fabricmc:yarn:1.16.5+build.5 : java.lang.RuntimeException: Failed to remap minecraft

**Comment by SirEnder125** [comment]
What do I `import` to use `Item` class?

**Comment by Technici4n** [comment]
You should ask on the #mod-dev channels on the official Discord server for this kind of help, it will be much more interactive.

**Comment by SirEnder125** [comment]
I do not have this "Discord" you speak of.

**Comment by OroArmor** [comment]
https://discord.gg/v6v4pMv

**Comment by SirEnder125** [comment]
And I do what there?

**Comment by OroArmor** [comment]
just join the discord for more focused and specific help. github issues are not for this kind of support.

**Comment by SirEnder125** [comment]
Aight.
