### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mod'!

### ISSUE THREAD

**Issue by PastaDogFX** [FabricMC/fabric-example-mod#89]
Hi again,

I made a new project and immediately ran downloadAssets and genEclipseRuns and ran the client and it worked! I brought my code from the previous project in and tried to run the client again. However, it failed, this tijme with an error saying: 

org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found

What could I do to fix this? Thanks,
Pasta

The full console print is available here: https://paste.gg/p/anonymous/24b6ad66080847f7a9f977d9419e5c46

**Comment by TheEpicBlock** [comment]
You most likely removed, renamed or changed the package of the ExampleMixin. Make sure your mixin.json is correct.

**Comment by PastaDogFX** [comment]
I changed the package to com.pastadog.mod.mixin and I'm waiting to change the mixin class, is that what I did wrong?

**Comment by OroArmor** [comment]
change the package in `modid.mixins.json`

**Comment by PastaDogFX** [comment]
Hi,

This helped get rid of an error but a new one popped up, and I was hoping you could take a look at it: https://paste.gg/p/anonymous/9969b4c3efde4b9fb5268922b3d4ff55

**Comment by CoolDude180** [comment]
Hello, I have this same issue as of now and I can't seem to find a solution anywhere on Google. Have you found out the problem and how to resolve it? If yes, could you share it?

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
