### ISSUE TITLE
Proposal: create new branch for Kotlin

### ISSUE THREAD

**Issue by valerie-makes** [FabricMC/fabric-example-mod#94]
Currently for Kotlin, the [tutorial:setup page on the wiki](https://fabricmc.net/wiki/tutorial:setup) points to [natanfudge's unofficial repository](https://github.com/natanfudge/fabric-example-mod-kotlin), and it seems like an official template doesn't exist.

I propose creating a new branch in this repository for Kotlin so that there's an official template which can be maintained alongside the existing Java version. Using the same repository also means that non-Java-specific improvements to the main branch can be easily merged/rebased into the Kotlin branch.

I'm happy to open a Kotlin PR if this sounds like a good idea? It might have to be merged manually because GitHub doesn't allow creating a new branch in the target repository directly from a PR as far as I'm aware.

**Comment by modmuss50** [comment]
I think a seprate issue would make more sense for this.

**Comment by davidbailey00** [comment]
Okay, is there anything I could do to help out with that?

**Comment by modmuss50** [comment]
This is handled by the new template generator I am working on: https://github.com/FabricMC/fabricmc.net/pull/3
