### ISSUE TITLE
Error: Could not resolve all files for configuration ':modCompileClasspath'.

### ISSUE THREAD

**Issue by cybrpop** [FabricMC/fabric-example-mod#97]
So, i have been learning to make a mod but while running gradlew, I'm getting this error.
![image](https://user-images.githubusercontent.com/80264293/115118649-d53d4900-9fc1-11eb-8d91-c8862d50413b.png)

**Comment by actuallyasmartname** [comment]
Fabric API is `32.5+1.16`, not `0.32.5+1.16` 😃

**Comment by actuallyasmartname** [comment]
I can build fine..

**Comment by cybrpop** [comment]
oh, which jdk you're using?

**Comment by actuallyasmartname** [comment]
jdk 11

**Comment by actuallyasmartname** [comment]
try 0.33.0+1.16

**Comment by cemerson** [comment]
I was targeting MC 1.17.1 and having a similar error. Changing my gradle.properties from 0.38.2+1.17 to 0.33.0+1.16 (suggested above) fixed the issue for me (for now)! Thank you!
