### ISSUE TITLE
I cant compile my mod

### ISSUE THREAD

**Issue by BrennoMaturino1** [FabricMC/fabric-example-mod#98]
When i try to compile i get this error:

`Downloads\fabric-example-mod-master\fabric-example-mod-master> .\gradlew vscode

> Configure project :
Fabric Loom: 0.6.57 Build(release #57)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fabric-example-mod-master'.
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find net.fabricmc:fabric-loader:0.32.5+1.16.
     Searched in the following locations:
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/build/loom-cache/fabric-loader-0.32.5+1.16.jar
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/build/loom-cache/fabric-loader.jar 
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/.gradle/loom-cache/remapped_mods/net/fabricmc/fabric-loader/0.32.5+1.16/fabric-loader-0.32.5+1.16.pom
       - https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.32.5+1.16/fabric-loader-0.32.5+1.16.pom
       - https://libraries.minecraft.net/net/fabricmc/fabric-loader/0.32.5+1.16/fabric-loader-0.32.5+1.16.pom
       - https://repo.maven.apache.org/maven2/net/fabricmc/fabric-loader/0.32.5+1.16/fabric-loader-0.32.5+1.16.pom
       - file:/C:/Users/brenn/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2/fabric-loader-0.32.5+1.16.jar
       - file:/C:/Users/brenn/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2/fabric-loader.jar   
     Required by:
         project :
   > Could not find net.fabricmc.fabric-api:fabric-api:0.11.3.
     Searched in the following locations:
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/build/loom-cache/fabric-api-0.11.3.jar
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/build/loom-cache/fabric-api.jar    
       - file:/C:/Users/brenn/Downloads/fabric-example-mod-master/fabric-example-mod-master/.gradle/loom-cache/remapped_mods/net/fabricmc/fabric-api/fabric-api/0.11.3/fabric-api-0.11.3.pom
       - https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/0.11.3/fabric-api-0.11.3.pom
       - https://libraries.minecraft.net/net/fabricmc/fabric-api/fabric-api/0.11.3/fabric-api-0.11.3.pom
       - https://repo.maven.apache.org/maven2/net/fabricmc/fabric-api/fabric-api/0.11.3/fabric-api-0.11.3.pom
       - file:/C:/Users/brenn/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2/fabric-api-0.11.3.jar
       - file:/C:/Users/brenn/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2/fabric-api.jar      
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan 
to get full insights.

* Get more help at https://help.gradle.org`

**Comment by Technici4n** [comment]
Hello, it seems you swapped versions of fabric loader and fabric API. You are trying to load API version 0.11.3 and loader version 0.32.5+1.16, but it should be the opposite.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
